Repository ithaka/pharos, pull requests merged in 2022-07, with the labels that each got.

#366 ImageCard: Selectable and disabled variants, new styling for error variant
  .changeset/pink-needles-jump.md
  packages/pharos/src/components/image-card/pharos-image-card.scss
  packages/pharos/src/components/image-card/pharos-image-card.test.ts
  packages/pharos/src/components/image-card/pharos-image-card.ts
  packages/pharos/src/components/image-card/pharos-image-card.wc.stories.mdx
Labels: component/image-card

#369 chore(deps): update Storybook package versions
  .storybook/babel.config.js
  package.json
  packages/pharos-site/babel.config.js
  yarn.lock
Labels: status/code review, dependencies

#370 fix(build): add commit logging in build ignore script
  build-ignore.sh
Labels: infrastructure, status/code review

#371 fix(build): always build if the compared commits are the same
  build-ignore.sh
Labels: infrastructure, status/code review

#372 fix(build): use proper exit code
  build-ignore.sh
Labels: infrastructure, status/code review

#373 ImageCard: Use gray background on selectable disabled card
  .changeset/small-beers-double.md
  packages/pharos/src/components/image-card/pharos-image-card.ts
Labels: status/code review, component/image-card

#375 feat(icon): Add new profile icon
  .changeset/pretty-seahorses-smash.md
  packages/pharos/assets/icons/profile.svg
  packages/pharos/tokens/assets/icons.json
Labels: status/ready to test, component/icon

#380 fix(docs): redirect iconography button to storybook icons page
  .changeset/thirty-hairs-bow.md
  packages/pharos-site/src/pages/brand-expressions/iconography.mdx
Labels: documentation, note/bug fix
