Repository ithaka/pharos, pull requests merged in 2022-06, with the labels that each got.

#345 add registry polyfill info to getting started
  packages/pharos-site/src/pages/getting-started.mdx
Labels: documentation

#359 fix(chromatic): update delays for visual snapshot tests
  packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.wc.stories.mdx
  packages/pharos/src/components/toast/pharos-toast.wc.stories.mdx
  packages/pharos/src/components/tooltip/pharos-tooltip.wc.stories.mdx
Labels: infrastructure, note/bug fix

#360 Fix ITHAKA organizational links
  .changeset/tough-buttons-pull.md
  README.md
  packages/pharos-site/src/components/footer.tsx
  packages/pharos-site/src/pages/index.tsx
  packages/pharos/docs/1.intro.docs.stories.mdx
Labels: documentation, status/code review, ithaka/pharos-site
