Repository ithaka/pharos, pull requests merged in 2023-09, with the labels that each got.

#599 Dropdown: add line rules for light variants
  .changeset/eleven-spoons-battle.md
  packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.scss
  packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.scss
Labels: status/code review

#605 Bump dependencies and update resolutions
  package.json
  packages/pharos/package.json
  yarn.lock
Labels: status/code review, dependencies

#606 Tokens: improve glacier-blue-40 AAA color contrast
  .changeset/fresh-wolves-rule.md
  packages/pharos/tokens/color/base.json
Labels: status/code review, accessibility, design tokens, status/needs design input

#607 docs: add @sirrah-tam as a contributor
  .all-contributorsrc
  README.md
Labels: documentation

#603 Sheet: Component Contribution
  .changeset/blue-masks-retire.md
  .storybook/initComponents.js
  packages/pharos/src/components/sheet/PharosSheet.react.stories.jsx
  packages/pharos/src/components/sheet/pharos-sheet.scss
  packages/pharos/src/components/sheet/pharos-sheet.test.ts
  packages/pharos/src/components/sheet/pharos-sheet.ts
  packages/pharos/src/components/sheet/pharos-sheet.wc.stories.jsx
  packages/pharos/src/index.ts
  packages/pharos/src/test/initComponents.ts
Labels: status/code review, component/sheet

#613 Sheet: Add overflow for long content and remove footer
  .changeset/fresh-parrots-judge.md
  packages/pharos/src/components/sheet/PharosSheet.react.stories.jsx
  packages/pharos/src/components/sheet/pharos-sheet.scss
  packages/pharos/src/components/sheet/pharos-sheet.test.ts
  packages/pharos/src/components/sheet/pharos-sheet.ts
  packages/pharos/src/components/sheet/pharos-sheet.wc.stories.jsx
Labels: status/code review

#614 Remove `paint` value from contain properties
  .changeset/five-moles-add.md
  packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.scss
  packages/pharos/src/components/footer/pharos-footer.scss
  packages/pharos/src/components/input-group/pharos-input-group.scss
  packages/pharos/src/components/modal/pharos-modal.scss
  packages/pharos/src/components/select/pharos-select.scss
  packages/pharos/src/components/sheet/pharos-sheet.scss
  packages/pharos/src/components/sidenav/pharos-sidenav-menu.scss
  packages/pharos/src/components/sidenav/pharos-sidenav-section.scss
  packages/pharos/src/components/tabs/pharos-tab.scss
Labels: note/bug fix, status/code review, BREAKING

#617 Sheet: Update default height and emit event for expand and collapse
  .changeset/thick-bugs-sing.md
  packages/pharos/src/components/sheet/pharos-sheet.scss
  packages/pharos/src/components/sheet/pharos-sheet.ts
Labels: status/code review, component/sheet

#608 Coach Mark: Component contribution
  .all-contributorsrc
  .changeset/sour-knives-poke.md
  .storybook/initComponents.js
  README.md
  packages/pharos-site/initComponents.tsx
  packages/pharos-site/src/pages/components/coach-mark/index.mdx
  packages/pharos-site/static/guidelines/coach-mark.docs.mdx
  packages/pharos/src/components/coach-mark/PharosCoachMark.react.stories.jsx
  packages/pharos/src/components/coach-mark/pharos-coach-mark.scss
  packages/pharos/src/components/coach-mark/pharos-coach-mark.test.ts
  packages/pharos/src/components/coach-mark/pharos-coach-mark.ts
  packages/pharos/src/components/coach-mark/pharos-coach-mark.wc.stories.jsx
  packages/pharos/src/components/coach-mark/storyArgs.ts
  packages/pharos/src/index.ts
  packages/pharos/src/test/initComponents.ts
  packages/pharos/tokens/components/coach-mark.json
Labels: status/code review, component/coach-mark
