Repository ithaka/pharos, pull requests merged in 2024-04, with the labels that each got.

#739 Add individual component exports
  .changeset/warm-nails-eat.md
  packages/pharos/package.json
Labels: status/code review

#742 Update Storybook to v8
  .storybook/main.ts
  .yarn/install-state.gz
  package.json
  packages/pharos/src/components/toast/pharos-toaster.ts
  yarn.lock
Labels: status/code review, storybook

#743 chore(deps): bump dependencies
  .yarn/install-state.gz
  package.json
  packages/pharos-cli/package.json
  packages/pharos-site/package.json
  packages/pharos/package.json
  yarn.lock
Labels: dependencies
