Repository ithaka/pharos, pull requests merged in 2024-06, with the labels that each got.

#764 chore(deps): bump dependencies
  .yarn/install-state.gz
  package.json
  packages/pharos-cli/package.json
  packages/pharos-site/package.json
  packages/pharos/package.json
  yarn.lock
Labels: status/code review, dependencies

#766 Card: Improve accessibility by moving overlay slot outside of <a> tag
  .changeset/red-parents-dream.md
  .yarn/install-state.gz
  packages/pharos/src/components/image-card/PharosImageCard.react.stories.jsx
  packages/pharos/src/components/image-card/pharos-image-card.scss
  packages/pharos/src/components/image-card/pharos-image-card.ts
  packages/pharos/src/components/image-card/pharos-image-card.wc.stories.jsx
Labels: note/bug fix, component/image-card

#770 Create form data export
  .all-contributorsrc
  .changeset/cold-crews-occur.md
  packages/pharos/package.json
Labels: infrastructure, note/bug fix
