Repository ithaka/pharos, pull requests merged in 2024-05, with the labels that each got.

#752 chore(deps): bump deps
  .stylelintrc.js
  .yarn/install-state.gz
  package.json
  packages/pharos-cli/package.json
  packages/pharos-site/package.json
  packages/pharos/package.json
  packages/pharos/src/utils/scss/_mixins.scss
  yarn.lock
Labels: status/code review, dependencies

#754 fix(eslint): update linting ignore patterns
  .yarn/install-state.gz
  eslint.config.mjs
  package.json
  packages/pharos-cli/package.json
  packages/pharos/package.json
  yarn.lock
Labels: note/bug fix, status/code review

#761 fix(tabs): allow scrolling the panel contents
  .changeset/gorgeous-ducks-give.md
  .yarn/install-state.gz
  packages/pharos/src/components/tabs/pharos-tabs.scss
Labels: note/bug fix, component/tabs
