Repository ithaka/pharos, pull requests merged in 2025-01, with the labels that each got.

#844 feat(sidenav): update close button
  .changeset/silver-suits-wait.md
  packages/pharos/src/components/sidenav/pharos-sidenav.scss
  packages/pharos/src/components/sidenav/pharos-sidenav.ts
Labels: status/code review

#843 feat(icon): add rotate icon
  .changeset/chilly-buttons-switch.md
  packages/pharos/assets/icons/rotate.svg
  packages/pharos/tokens/assets/icons.json
Labels: status/code review

#846 feat(sidenav): use large icon
  .changeset/selfish-toys-do.md
  packages/pharos/src/components/sidenav/pharos-sidenav.ts
Labels: status/ready to test

#842 Icon: Add "filetype html" icon
  .changeset/early-rabbits-sip.md
  packages/pharos/assets/icons/filetype-html.svg
  packages/pharos/tokens/assets/icons.json
Labels: component/icon

#850 chore(infra): add dependabot schedule
  .github/dependabot.yml
Labels: status/code review, dependencies

#849 chore(deps): update deps
  package.json
  packages/pharos-cli/package.json
  packages/pharos-site/package.json
  packages/pharos/package.json
  packages/pharos/scripts/build-styles.js
  packages/pharos/src/components/coach-mark/pharos-coach-mark.scss
  packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.scss
  packages/pharos/src/components/link/pharos-link.scss
  packages/pharos/src/components/popover/pharos-popover.scss
  packages/pharos/src/components/sidenav/pharos-sidenav-menu.scss
  packages/pharos/web-test-runner.config.mjs
  yarn.lock
Labels: status/code review, dependencies

#858 chore(deps): ignore react and react-dom updates
  .github/dependabot.yml
Labels: status/code review

#867 fix(dependabot): ignore @babel/core updates for the moment
  .github/dependabot.yml
Labels: status/code review, dependencies
