Repository ithaka/pharos, pull requests merged in 2025-04, with the labels that each got.

#925 chore: update build target to es2022
  .changeset/funny-hotels-fold.md
  packages/pharos-cli/tsconfig.json
  packages/pharos-site/babel.config.js
  packages/pharos-site/tsconfig.json
  packages/pharos/tsconfig.json
Labels: infrastructure, status/code review

#927 feat(icon): update cite svg
  .all-contributorsrc
  .changeset/long-games-live.md
  README.md
  packages/pharos/assets/icons/cite.svg
Labels: status/code review, component/icon

#928 chore(icon): lint SVG files on pre-commit
  lint-staged.config.js
Labels: status/code review
